config/routes.rb
Dineout::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users

  resources :events
  root to: 'start#index'

  match '/events/:id/participate', :to => 'events#participate', :as => 'participate_event'

  resources :diners
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
        if user.has_role?(:admin)
            #Admins
            can :manage, :all
        else
            #Users
            can :read, :all
            can :manage, Event
            cannot :delete, Event
            can :delete, Event, user_id: user.id             
            can :manage, Diner
            cannot :delete, Diner
        end
    else
        #Guests
        can :read, :all 
    end
  end
end

app/models/diner.rb
class Diner < ActiveRecord::Base
 attr_accessible :city, :name, :number, :phone, :street, :time, :url, :urlmaps, :zipcode, :diner_type_id, :mealtype_ids, :diner_type, :mealtypes 

  has_many :events
  has_and_belongs_to_many :mealtypes
  belongs_to :diner_type

  validates_presence_of :name, :city, :number, :street, :zipcode
  validates :urlmaps, format: %r|^http(s?)://maps.google.de/|

  def self.type_search(type_search)
    if type_search and type_search != "-1"
      where( :diner_type_id => type_search )
    else
      scoped
    end    
  end

end

app/models/diner_type.rb
class DinerType < ActiveRecord::Base
  attr_accessible :name 

  has_many :diners
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :dtime, :diner_id, :user_id, :user_ids
  belongs_to :diner
  belongs_to :user
  
  has_many :participations
  has_many:users, through: :participations

  validates_presence_of :diner

end

app/models/mealtype.rb
class Mealtype < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :diners
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role_ids
  # attr_accessible :title, :body
  has_many :events

  has_many :participations
  has_many:events, through: :participations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_admin_user!
    redirect_to new_user_session_path unless can?(:manage, :all)
  end
end

app/controllers/diners_controller.rb
class DinersController < ApplicationController
  load_and_authorize_resource 
  # GET /diners
  # GET /diners.json
  def index
    @diners = Diner.type_search(params[:type_search]).page(params[:page]).order('name ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diners }
    end
  end

  # GET /diners/1
  # GET /diners/1.json
  def show
    @diner = Diner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diner }
    end
  end

  # GET /diners/new
  # GET /diners/new.json
  def new
    @diner = Diner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diner }
    end
  end

  # GET /diners/1/edit
  def edit
    @diner = Diner.find(params[:id])
  end

  # POST /diners
  # POST /diners.json
  def create
    @diner = Diner.new(params[:diner])

    respond_to do |format|
      if @diner.save
        format.html { redirect_to @diner, notice: 'Diner was successfully created.' }
        format.json { render json: @diner, status: :created, location: @diner }
      else
        format.html { render action: "new" }
        format.json { render json: @diner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diners/1
  # PUT /diners/1.json
  def update
    params[:diner][:mealtype_ids] ||=[]
    @diner = Diner.find(params[:id])

    respond_to do |format|
      if @diner.update_attributes(params[:diner])
        format.html { redirect_to @diner, notice: 'Diner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diners/1
  # DELETE /diners/1.json
  def destroy
    @diner = Diner.find(params[:id])
    @diner.destroy

    respond_to do |format|
      format.html { redirect_to diners_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  # GET /events
  # GET /events.json
  def index
    @events = Event.find(:all, :conditions => ["date(dtime) = ?", Date.today], :order => 'dtime ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event.user = current_user 
    @event.users << current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def participate
    @event = Event.find(params[:id])
    @event.users << current_user 
    @event.save 
    redirect_to action: :show, id: @event.id 
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/start_controller.rb
class StartController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diners_helper.rb
module DinersHelper
	def iframe_urls(diner)
		diner.urlmaps + "&output=embed"
	end	
end

app/helpers/events_helper.rb
module EventsHelper
	def iframe_url(event)
		event.diner.urlmaps + "&output=embed"
	end
end

app/helpers/mealtype_helper.rb
module MealtypeHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/diners/_form.html.haml
= form_for(@diner, :html => { :class => 'form-horizontal' }) do |f|
  - if @diner.errors.any?
    #error_explanation
      %h2= "#{pluralize(@diner.errors.count, "error")} prohibited this diner from being saved:"
      %ul
        - @diner.errors.full_messages.each do |msg|
          %li= msg
  %div.control-group
  .field
    = f.label "Name", :class => 'control-label'
    %div.controls
      = f.text_field :name
  %div.control-group
  .field
    = f.label "Straße", :class => 'control-label'
    %div.controls
      = f.text_field :street
  %div.control-group
  .field
    = f.label "Hausnummer", :class => 'control-label'
    %div.controls
      = f.text_field :number
  %div.control-group  
  .field
    = f.label "PLZ", :class => 'control-label'
    %div.controls
      = f.text_field :zipcode
  %div.control-group 
  .field
    = f.label "Stadt", :class => 'control-label'
    %div.controls
      = f.text_field :city
  %div.control-group 
  .field
    = f.label "Webseite", :class => 'control-label'
    %div.controls
      = f.text_field :url
  %div.control-group 
  .field
    = f.label "Öffnungszeiten", :class => 'control-label'
    %div.controls
      = f.text_area :time, :rows => '5'
  %div.control-group 
  .field
    = f.label "Telefonnummer", :class => 'control-label'
    %div.controls
      = f.text_field :phone
  %div.control-group 
  .field
    = f.label "Art des Diners", :class => 'control-label'
    %div.controls
      = f.collection_select :diner_type_id, DinerType.order('name ASC').all, :id, :name, { selected: @diner.diner_type_id }, { multiple: false }
  %div.control-group 
  .field
    = f.label "Art der Gerichte", :class => 'control-label'
    - for mealtype in Mealtype.find(:all, :order => 'name ASC')
      %div.controls
        = check_box_tag "diner[mealtype_ids][]", mealtype.id, @diner.mealtypes.include?(mealtype)
        = mealtype.name
  %div.control-group 
  .field
    = f.label "Google Maps", :class => 'control-label'
    %div.controls
      = f.text_field :urlmaps
  .actions
    = f.submit 'Speichern'

app/views/diners/edit.html.haml
%h1 Diner bearbeiten

= render 'form'

= link_to 'Anzeigen', @diner
\|
= link_to 'Zurück', diners_path

app/views/diners/index.html.haml
%h1 Deine Diners

%form.form-inline
  %p
    %select.span3{:name => "type_search"}
      %option{:value => "-1"} Wähle eine Dinerart
      - d = DinerType.order('name ASC').all
      - d.each do |type|      
        %option{:value => type.id} 
          = type.name
    %button.btn{:type => "submit"} Filtern

%table.table.table-striped
  %tr
    %th Name
    %th Straße
    %th Stadt
    - if can?(:read, Diner)
      %th
    - if can?(:update, Diner)
      %th
    - if can?(:delete, Diner)
      %th

  - @diners.each do |diner|
    %tr
      %td= diner.name
      %td= diner.street
      %td= diner.city
      - if can?(:read, Diner)
        %td.icon-list= link_to ' Detailansicht', diner
      - if can?(:update, Diner)
        %td.icon-repeat= link_to ' Bearbeiten', edit_diner_path(diner)
      - if can?(:delete, Diner)
        %td.icon-remove-sign= link_to ' Entfernen', diner, method: :delete, data: { confirm: 'Are you sure?' }

%br
- if can?(:create, Event)
  = link_to 'Neues Diner anlegen', new_diner_path, :class => "btn"

app/views/diners/new.html.haml
%h1 Neues Diner
= render 'form'

= link_to 'Zurück', diners_path

app/views/diners/show.html.haml
%p#notice= notice

%h1 
  =@diner.name
%p
  %b Straße:
  = @diner.street
%p
  %b Hausnummer:
  = @diner.number
%p
  %b PLZ:
  = @diner.zipcode
%p
  %b Stadt:
  = @diner.city
%p
  %b Webseite:
  =link_to @diner.url
%p
  %b Öffnungszeiten:
  = @diner.time
%p
  %b Telefonnummer:
  = @diner.phone
%p
  %b Art des Diners:
  = @diner.diner_type.try(:name)
%p
  %b Art der Gerichte:
  - @diner.mealtypes.each do |mealtype|     
    = mealtype.name
%p
  %iframe{ width: 600, height: 400, frameborder: 0, scrolling: 'no', marginheight: 0, marginwidht: 0, src: iframe_urls(@diner) }

- if can?(:update, @event)
  = link_to 'Ändern', edit_diner_path(@diner)
  \|
= link_to 'Zurück', diners_path

app/views/events/_form.html.haml
= form_for(@event, :html => { :class => 'form-horizontal' }) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field.form-inline.muted
    = f.label 'erstellt von '
    - if @event.user != nil 
      = f.label @event.user.try(:username) 
    -else
      = f.label current_user.username 

  %div.control-group
  .field
    = f.label 'Diner', :class => 'control-label'
    %div.controls
    = f.collection_select :diner_id, Diner.order('name ASC').all, :id, :name, { selected: @event.diner_id }, { multiple: false }
  %div.control-group
  .field
    = f.label 'Uhrzeit', :class => 'control-label'
    %div.controls
    = f.time_select :dtime
  %div.control-group 
  .field
    = f.label "Teilnehmer", :class => 'control-label'
    %div.controls
    - @event.users.each do |user|
      = user.username
    
  %div.control-group 
  .actions
    = f.submit 'Speichern' 

app/views/events/edit.html.haml
%h1 Event bearbeiten

= render 'form'

= link_to 'Detailansicht', @event
\|
= link_to 'Zurück', events_path

app/views/events/index.html.haml
%h1 Deine Events

%table.table.table-hover
  %tr
    %th Diner
    %th Uhrzeit
    %th Teilnehmer
    %th Dabei
    %th 
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.diner.name
      %td= event.dtime.strftime("%H:%M")
      %td= event.users.count
      %td
        - if event.users.include?(current_user)        
          %p.icon-ok
      %td 
        - if can?(:read, event)
          %p.icon-list= link_to '  Detailansicht', event
      %td
        - if can?(:update, event) and event.user == current_user
          %p.icon-repeat= link_to '  Bearbeiten', edit_event_path(event)
      %td
        - if can?(:delete, event)
          %p.icon-remove-sign= link_to '  Entfernen', event, method: :delete, data: { confirm: 'Are you sure?' }
      %td
        - if current_user != nil and !event.users.include?(current_user)
          %p.icon-share-alt= link_to ' Teilnehmen', participate_event_path(event.id), :method => :post     

%br
- if can?(:create, Event)
  = link_to 'Neues Event anlegen', new_event_path, :class => "btn"

app/views/events/new.html.haml
%h1	Dein neues Event

= render 'form'

= link_to 'Zurück', events_path

app/views/events/show.html.haml
%p#notice= notice
%h1 Event

%p
  - if can?(:update, @event) and !@event.users.include?(current_user)
    = link_to ' Am Event teilnehmen', participate_event_path(@event.id), :method => :post, :class => "btn"

%p
  %b Diner:
  = @event.diner.name
%p
  %b Uhrzeit:
  = @event.dtime.strftime("%H:%M")
%p
  %b Ersteller:
  = @event.user.username
%p
  %b Teilnehmer:
  - @event.users.each do |user|
    = user.username
%p
  %iframe{ width: 600, height: 400, frameborder: 0, scrolling: 'no', marginheight: 0, marginwidth: 0, src: iframe_url(@event) }

%p
- if can?(:update, @event)
  = link_to 'Ändern', edit_event_path(@event)
  \|
= link_to 'Zurück', events_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Dineout"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body

    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %ul.nav
            %li= link_to(image_tag("dineOut.png", :width => "140"), :root)
            %li.myNavMargin= link_to "Events", "/events"
            %li.myNavMargin= link_to "Diners", "/diners"
            - if current_user != nil && current_user.has_role?(:admin)
              %li.myNavMargin= link_to "Administration", "/admin"
          %ul.nav.pull-right  
            - if current_user
              %li.myNavMargin= link_to current_user.username, edit_user_registration_path
              %li.myNavMargin= link_to 'Abmelden', destroy_user_session_path, method: :delete
            - else
              %li.myNavMargin= link_to 'Anmelden', new_user_session_path
              %li.myNavMargin= link_to 'Registrieren', new_user_registration_path
    .container-fluid

      .row-fluid          
        .span9
          = yield
    
      %footer
        %p
        %p &copy; dineOut 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/start/index.html.haml
%header{:style => 'float: left'}

  -if current_user
    %h1 Willkommen #{current_user.username}
    %br
    %h4 
      Wenn du deinen Mittag koordinieren möchtets,
      %br dann ist dineOut genau das richtige für dich!
      %br Probiere es einfach aus!
    
    %br
  -else
    %h1 Willkommen bei dineOut 
    %br
    %h4 
      Wenn du deinen Mittag koordinieren möchtets,
      %br dann ist dineOut genau das richtige für dich!
      %br Probiere es einfach aus!
    
    %br
    = link_to 'Registrieren', new_user_registration_path, :class => 'btn-large btn'
    = link_to 'Anmelden', new_user_session_path, :class => 'btn-large btn'

%br
%br
%br
  =image_tag("dineOut.png", :width => "350")  
  